### ISSUE TITLE
silent failure

### ISSUE THREAD

**Issue by berndhs** [maks/MGit#104]
I try to clone one of my existing repos, and I get an exception during the download.

There is no way to see what the exception is. This means I have no way to firx it.
That is substandard behaviour man. So I can't use the app.

**Comment by maks** [comment]
Thank you for reporting the issue. 
Yes, the app should not swallow exceptions.I thought I already had an issue to fix that, but it seems not.
I'll most likely log errors to a file, with a dialog that will tell you when an error has occurred that it has been logged to that file and suggesting that it be attached to a new or existing issue here on github.

**Comment by maks** [comment]
This should be fixed as of https://github.com/maks/MGit/pull/133

**Comment by Joncom** [comment]
It appears this is not fixed? Just installed the app and tried cloning my repo. I get an "Invalid Remote" error, which says "Clone failed" below in smaller text, and no additional information. I determined the problem to be an incorrect path (just like in #106), but please can't the app be more descriptive about what went wrong. I feel like the error message should actually tell users something like "no repository exists there".

**Comment by maks** [comment]
@Joncom thanks for reporting this. This issue was specifically about no error message being displayed to users, not about it being descriptive enough. Could you please open a new issue for this and I'll look into it, thanks.

**Comment by Joncom** [comment]
@maks Thanks for quick response. #406
