### ISSUE TITLE
Remove dependency on Google Play Services

### ISSUE THREAD

**Issue by maks** [maks/MGit#288]
MGit now has a dependency of Play Services in order to be able to use an up to date version of OpenSSL as required for HTTPS to Github and possibly other git service providers.
However Play services uses Conscrypt internally to do this so it should be possible to remove the dependency on Play services (which is problematic for publishing via F-Droid) and just use Conscrypt directly.

**Comment by kaeptmblaubaer1000** [comment]
This is now on #302.

**Comment by maks** [comment]
Fixed in #302

**Comment by kaeptmblaubaer1000** [comment]
@maks great, but still not released so we currently won't get it into F-Droid.

**Comment by maks** [comment]
Yes, I'll tag a release shortly do that it can be built by F-droid for distribution to people getting the app via it.
